### ISSUE TITLE
Improve installation instructions

### ISSUE THREAD

**Issue by Zettt** [rjames86/download_pinboard#4] opened 2015-04-19 05:47 UTC
In my case I had to install PyObjC and python-dateutil with pip. I'm using Homebrew. Been told by a friend, whom I'm with at the moment, that PyObjC is outdated. Not 100% sure why it was needed in the first place.

**Comment by rjames86** [comment] 2015-04-19 15:58
I'm using PyObjC since it was the nicest way to do Finder tagging and writing to `defaults`. There really isn't an elegant way to do it otherwise.

I can look into changing it, but this is the first report I've seen. I'm pretty sure PyObjC comes bundled with OS X, so I'm surprised you got these warnings. Same with `dateutil`

**Comment by Zettt** [comment] 2015-04-20 04:36
I'm too. I think it's all because of Homebrew.

**Comment by rjames86** [comment] 2015-06-21 00:17
Duplicate of issue [#5](https://github.com/rjames86/download_pinboard/issues/5)

Looks like installing PyObj solves this.

**Closed by rjames86** 2015-06-21 00:17 UTC
